name: Publish packages to PyPI

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.7"
    - name: Install dependencies
      run: |
        pip install --index-url 'https://:2020-01-30@time-machines-pypi.sealsecurity.io/' "setuptools >= 40.9"
        pip install --index-url 'https://:2020-01-30@time-machines-pypi.sealsecurity.io/' .
        pip install --index-url 'https://:2020-01-30@time-machines-pypi.sealsecurity.io/' --force-reinstall "setuptools >= 40.9"
    - name: Create packages
      run: python setup.py sdist bdist_wheel
    - name: Upload packages
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/*
        if-no-files-found: error
